In [5]:
# Relu
import numpy as np

inputs=np.array([1,2,-4,0,-8,-100,1])
output=[]
for i in inputs:
#     This is the ground implementation of ReLu activation function
#     if i>0:
#         output.append(i)
#     elif i<=0:
#         output.append(0)
# output
# The Equation for ReLu activation function
    output.append(max(0,i))
output

[1, 2, 0, 0, 0, 0, 1]

In [2]:
# Using Relu with class
# import nnfs
# from nnfs.dataset import spiral_data
# nnfs.init()
import numpy as np
np.random.seed(0)
X=np.array([[1,2,3,2.5],
            [2.0,5.0,-1.0,2.0],
            [-1.5,2.7,3.3,-0.8]])
class Dense_Layer:
    def __init__(self,n_input,n_neuron):
        self.weight=0.10*(np.random.randn(n_input,n_neuron))
        self.biases=np.zeros((1,n_neuron))
    def forward_pass(self,inputs):
        self.output=np.dot(inputs,self.weight)+self.biases
# print(np.random.randn(3,4))
# layer1=Dense_Layer(4,4)
# layer2=Dense_Layer(4,5)

# layer1.forward_pass(X)
# layer2.forward_pass(layer1.output)
# print(layer2.output)
# Working with relu activation function
class Relu_Activation:
    def forward(self,inputs):
        self.output=np.maximum(0,inputs)
class Sigmoid:
    def forward(self,inputs):
        exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
        probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
        self.output=probabilities
# X,y=spiral_data(samples=100,classes=3)    
# layer1=Dense_Layer(4,5)
# activationRelu=Relu_Activation()
# layer1.forward_pass(X)
# activationRelu.forward(layer1.output)

# sigmoid_activation=Sigmoid()
# sigmoid_activation.forward(activationRelu.output)
# print(sigmoid_activation.output[:3])

In [25]:
import nnfs
from nnfs.datasets import spiral_data
X,y=spiral_data(samples=100,classes=3)
dense1=Dense_Layer(2,3)

dense1.forward_pass(X)
activation1=Relu_Activation()
activation1.forward(dense1.output)

dense2=Dense_Layer(3,3)
dense2.forward_pass(activation1.output)
activation2=Sigmoid()
activation2.forward(dense2.output)
print(activation2.output[:5])

[[0.33333333 0.33333333 0.33333333]
 [0.33335808 0.33330256 0.33333936]
 [0.33333011 0.33331073 0.33335916]
 [0.33333986 0.33328997 0.33337017]
 [0.33335179 0.33326492 0.33338329]]
