In [1]:
# example of the max of a list of numbers
# define data
data = [1, 3, 2]
# calculate the max of the list
result = max(data)
print(result)

3


In [3]:
# example of the argmax of a list of numbers
import numpy as np
# define data
data =np.array([1, 3, 2])
# calculate the argmax of the list
result = np.argmax(data)
print(result)

1


In [4]:
# transform values into probabilities
from math import exp
# calculate each probability
p1 = exp(1) / (exp(1) + exp(3) + exp(2))
p2 = exp(3) / (exp(1) + exp(3) + exp(2))
p3 = exp(2) / (exp(1) + exp(3) + exp(2))
# report probabilities
print(p1, p2, p3)
# report sum of probabilities
print(p1 + p2 + p3)

0.09003057317038046 0.6652409557748219 0.24472847105479767
1.0


In [5]:

# example of a function for calculating softmax for a list of numbers
from numpy import exp
 
# calculate the softmax of a vector
def softmax(vector):
 e = exp(vector)
 return e / e.sum()
 
# define data
data = [1, 3, 2]
# convert list of numbers to a list of probabilities
result = softmax(data)
# report the probabilities
print(result)
# report the sum of the probabilities
print(sum(result))

[0.09003057 0.66524096 0.24472847]
1.0


In [7]:
# Practice section
import numpy as np
# Making an array
data=np.array([1,2,3,4])
# Finding the probability of each in the array
def softmax(inputs):
    e=exp(inputs)
    return e/e.sum()
result=softmax(data)
print(result)
print(sum(result))

[0.0320586  0.08714432 0.23688282 0.64391426]
1.0


In [27]:
import math
from numpy import exp
data=[1,2,3,0]
# finding the exponential values
E=math.e
output=[]
for i in data:
    output.append(E**i)
print(output)
# Now lets find the probabilities of each element in the list
normalize_sum=sum(output)
print(normalize_sum)
norm_values=[]
for values in output:
    norm_values.append(values/normalize_sum)
print(norm_values)
print(sum(norm_values))

[2.718281828459045, 7.3890560989306495, 20.085536923187664, 1.0]
31.19287485057736
[0.08714431874203257, 0.23688281808991013, 0.6439142598879722, 0.03205860328008499]
1.0


In [51]:
# Working with 2D array
data=np.array([[4.8,1.21,2.385],
               [8.9,-1.81,0.2],
               [1.41,1.051,0.026]])
output=np.exp(data)
# norm_values=output/np.sum(output)
norm_values=np.sum(output,axis=1,keepdims=True)
# print(output)
# print(sum(norm_values))
print(norm_values)
norm_output=output/norm_values
output1=(np.sum(norm_output,axis=1))
output1

[[ 135.72296484]
 [7333.35859605]
 [   7.98280655]]


array([1., 1., 1.])

In [59]:
c,y=spiral_data(classes=100,samples=3)

NameError: name 'spiral_data' is not defined